# Generated by Django 4.1.2 on 2026-08-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_item_cost_item_created_at_item_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='date_added',
            new_name='date_addedd',
        ),
    ]
