# Generated by Django 4.1.2 on 2026-08-03 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_rename_date_added_comments_date_addedd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='date_addedd',
            new_name='date_added',
        ),
    ]
