# Generated by Django 5.2.17 on 2026-08-26 20:48
# Manually augmented (Phase 1 pgvector support):
#   - The autodetector originally folded the HnswIndex into ItemEmbedding's
#     CreateModel(options={'indexes': [...]}). That's unsafe: Django's
#     schema_editor.create_model() unconditionally emits deferred SQL for every
#     index declared on a model at creation time (see
#     BaseDatabaseSchemaEditor.create_model -> self._model_indexes_sql(model)),
#     with no vendor check. On SQLite that would try to run
#     `CREATE INDEX ... USING hnsw (...)`, which is invalid syntax there and
#     crashes the test suite.
#   - Fix: the 'indexes' key was removed from CreateModel's options below (so the
#     table is created bare), and the HnswIndex is instead added via a trailing
#     SeparateDatabaseAndState block. Its state_operations keep Django's migration
#     *state* in sync with the model (Meta.indexes includes the same HnswIndex,
#     so `makemigrations --check` sees no drift), while its database_operations
#     use ConditionalAddIndex, which only emits real DDL on PostgreSQL.

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import HnswIndex, VectorExtension


class ConditionalAddIndex(migrations.AddIndex):
    """Only actually creates the index on PostgreSQL; no-ops elsewhere (e.g. SQLite tests)."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        # Must run before any operation references the `vector` column type
        # (VectorExtension() is vendor-safe: it no-ops on non-PostgreSQL
        # connections, see django.contrib.postgres.operations.CreateExtension).
        VectorExtension(),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='ItemEmbedding',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='catalog.item')),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('content_hash', models.CharField(max_length=64)),
                ('text_version', models.PositiveSmallIntegerField(default=1)),
                ('model_name', models.CharField(default='gemini-embedding-2', max_length=64)),
                ('source_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_item_embedding',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.item')),
            ],
            options={
                'db_table': 'product_item_attribute',
                'indexes': [models.Index(fields=['name', 'value'], name='product_ite_name_b34b56_idx')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='itemembedding',
                    index=HnswIndex(
                        name='item_embedding_hnsw_cos',
                        fields=['vector'],
                        m=16,
                        ef_construction=64,
                        opclasses=['vector_cosine_ops'],
                    ),
                ),
            ],
            database_operations=[
                ConditionalAddIndex(
                    model_name='itemembedding',
                    index=HnswIndex(
                        name='item_embedding_hnsw_cos',
                        fields=['vector'],
                        m=16,
                        ef_construction=64,
                        opclasses=['vector_cosine_ops'],
                    ),
                ),
            ],
        ),
    ]
