# Generated by Django 5.2.17 on 2026-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_description_alter_item_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
