# Generated by Django 5.2.17 on 2026-08-27 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingSyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('content_hash', models.CharField(max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_sync_tasks', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_embedding_sync_task',
                'indexes': [models.Index(fields=['status', 'created_at'], name='catalog_emb_status_70fe34_idx')],
            },
        ),
    ]
